[all]
localhost ansible_connection=local

[storage]
# Empty for now, but will be used to define storage servers in the future
virtual_machine ansible_host=local

#[other_group]
# Placeholder for other groups of servers in the future

[firewall_router]
virtual_machine ansible_host=local