- hosts: all
  roles:
  - devsec.hardening.ssh_hardening

- hosts: storage
  roles:
  - snapraid_mergerfs
  - samba

#- hosts: other_group
#  roles:
  # Placeholder for other roles in the future 