- hosts: all
  become: true
  roles:
  - sshd
  - fail2ban

- hosts: storage
#  roles:
#  - snapraid_mergerfs
#  - samba

- hosts: firewall_router
  roles:
  - firewall_vm

#- hosts: other_group
#  roles:
  # Placeholder for other roles in the future 