#snapraid_disks:
#  - { data: "/mnt/disk1", content: "/var/snapraid/content1" }
#  - { data: "/mnt/disk2", content: "/var/snapraid/content2" }
#snapraid_parity_disks:
#  - { data: "/mnt/disk3", content: "/var/snapraid/content3" }

#mergerfs_mounts:
#  - { path: "/mnt/storage", sources: "/mnt/disk1:/mnt/disk2" }

#samba_shares:
#  - { name: "media", path: "/mnt/storage/media" }


# Firewall-router configs
firewall_vm_wan_pci_address: '0000:00:04.0'
firewall_vm_image_url: "https://downloads.openwrt.org/releases/25.12.4/targets/x86/64/openwrt-25.12.4-x86-64-generic-targz-combined-efi.img.gz"
